/**
 * Copyright (c) 2015-2016, Michael Yang 杨福海 (fuhai999@gmail.com).
 *
 * Licensed under the GNU Lesser General Public License (LGPL) ,Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.jpress.jp.model.base;

import io.jpress.model.Metadata;
import io.jpress.model.core.JModel;
import io.jpress.model.query.MetaDataQuery;
import java.math.BigInteger;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.ehcache.CacheKit;
import com.jfinal.plugin.ehcache.IDataLoader;

/**
 *  Auto generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserContract<M extends BaseUserContract<M>> extends JModel<M> implements IBean {

	public static final String CACHE_NAME = "user_contract";
	public static final String METADATA_TYPE = "user_contract";

	public void removeCache(Object key){
		if(key == null) return;
		CacheKit.remove(CACHE_NAME, key);
	}

	public void putCache(Object key,Object value){
		CacheKit.put(CACHE_NAME, key, value);
	}

	public M getCache(Object key){
		return CacheKit.get(CACHE_NAME, key);
	}

	public M getCache(Object key,IDataLoader dataloader){
		return CacheKit.get(CACHE_NAME, key, dataloader);
	}

	public Metadata createMetadata(){
		Metadata md = new Metadata();
		md.setObjectId(getId());
		md.setObjectType(METADATA_TYPE);
		return md;
	}

	public Metadata createMetadata(String key,String value){
		Metadata md = new Metadata();
		md.setObjectId(getId());
		md.setObjectType(METADATA_TYPE);
		md.setMetaKey(key);
		md.setMetaValue(value);
		return md;
	}

	public boolean saveOrUpdateMetadta(String key,String value){
		Metadata metadata = MetaDataQuery.me().findByTypeAndIdAndKey(METADATA_TYPE, getId(), key);
		if (metadata == null) {
			metadata = createMetadata(key, value);
			return metadata.save();
		}
		metadata.setMetaValue(value);
		return metadata.update();
	}

	@Override
	public boolean equals(Object o) {
		if(o == null){ return false; }
		if(!(o instanceof BaseUserContract<?>)){return false;}

		BaseUserContract<?> m = (BaseUserContract<?>) o;
		if(m.getId() == null){return false;}

		return m.getId().compareTo(this.getId()) == 0;
	}

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		Object id = get("id");
		if (id == null)
			return null;

		return id instanceof BigInteger ? (BigInteger)id : new BigInteger(id.toString());
	}

	public void setAccountant(java.lang.String accountant) {
		set("accountant", accountant);
	}

	public java.lang.String getAccountant() {
		return get("accountant");
	}

	public void setAccountantMobile(java.lang.String accountantMobile) {
		set("accountant_mobile", accountantMobile);
	}

	public java.lang.String getAccountantMobile() {
		return get("accountant_mobile");
	}

	public void setService(java.lang.String service) {
		set("service", service);
	}

	public java.lang.String getService() {
		return get("service");
	}

	public void setServiceMobile(java.lang.String serviceMobile) {
		set("service_mobile", serviceMobile);
	}

	public java.lang.String getServiceMobile() {
		return get("service_mobile");
	}

	public void setUserId(java.math.BigInteger userId) {
		set("userId", userId);
	}

	public Integer getAid() {
		return get("aid");
	}
	public void setAid(Integer aid) {
		set("aid", aid);
	}


	public Integer getSid() {
		return  get("sid");
	}
	
	public void setSid(Integer sid) {
		set("sid", sid);
	}
	public java.math.BigInteger getUserId() {
		return get("userId");
	}
	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

}
