/**
 * Copyright (c) 2015-2016, Michael Yang 杨福海 (fuhai999@gmail.com).
 *
 * Licensed under the GNU Lesser General Public License (LGPL) ,Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.jpress.jp.model.base;

import io.jpress.model.Metadata;
import io.jpress.model.core.JModel;
import io.jpress.model.query.MetaDataQuery;
import java.math.BigInteger;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.ehcache.CacheKit;
import com.jfinal.plugin.ehcache.IDataLoader;

/**
 *  Auto generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProgress<M extends BaseProgress<M>> extends JModel<M> implements IBean {

	public static final String CACHE_NAME = "progress";
	public static final String METADATA_TYPE = "progress";

	public void removeCache(Object key){
		if(key == null) return;
		CacheKit.remove(CACHE_NAME, key);
	}

	public void putCache(Object key,Object value){
		CacheKit.put(CACHE_NAME, key, value);
	}

	public M getCache(Object key){
		return CacheKit.get(CACHE_NAME, key);
	}

	public M getCache(Object key,IDataLoader dataloader){
		return CacheKit.get(CACHE_NAME, key, dataloader);
	}

	public Metadata createMetadata(){
		Metadata md = new Metadata();
		md.setObjectId(getId());
		md.setObjectType(METADATA_TYPE);
		return md;
	}

	public Metadata createMetadata(String key,String value){
		Metadata md = new Metadata();
		md.setObjectId(getId());
		md.setObjectType(METADATA_TYPE);
		md.setMetaKey(key);
		md.setMetaValue(value);
		return md;
	}

	public boolean saveOrUpdateMetadta(String key,String value){
		Metadata metadata = MetaDataQuery.me().findByTypeAndIdAndKey(METADATA_TYPE, getId(), key);
		if (metadata == null) {
			metadata = createMetadata(key, value);
			return metadata.save();
		}
		metadata.setMetaValue(value);
		return metadata.update();
	}

	@Override
	public boolean equals(Object o) {
		if(o == null){ return false; }
		if(!(o instanceof BaseProgress<?>)){return false;}

		BaseProgress<?> m = (BaseProgress<?>) o;
		if(m.getId() == null){return false;}

		return m.getId().compareTo(this.getId()) == 0;
	}

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		Object id = get("id");
		if (id == null)
			return null;

		return id instanceof BigInteger ? (BigInteger)id : new BigInteger(id.toString());
	}

	public void setSetProgressId(java.math.BigInteger setProgressId) {
		set("setProgressId", setProgressId);
	}

	public java.math.BigInteger getSetProgressId() {
		return get("setProgressId");
	}

	public void setUserId(java.math.BigInteger userId) {
		set("userId", userId);
	}

	public java.math.BigInteger getUserId() {
		return get("userId");
	}

	public void setStepProgress(java.lang.String stepProgress) {
		set("step_progress", stepProgress);
	}

	public java.lang.String getStepProgress() {
		return get("step_progress");
	}

	public void setUploadMt(java.lang.String uploadMt) {
		set("uploadMt", uploadMt);
	}

	public java.lang.String getUploadMt() {
		return get("uploadMt");
	}

	public void setLactMt(java.lang.String lactMt) {
		set("lactMt", lactMt);
	}

	public java.lang.String getLactMt() {
		return get("lactMt");
	}

	public void setAddressMt(java.lang.String addressMt) {
		set("addressMt", addressMt);
	}

	public java.lang.String getAddressMt() {
		return get("addressMt");
	}

	public void setOperatorMt(java.lang.String operatorMt) {
		set("operatorMt", operatorMt);
	}

	public java.lang.String getOperatorMt() {
		return get("operatorMt");
	}

	public void setPhoneMt(java.lang.String phoneMt) {
		set("phoneMt", phoneMt);
	}

	public java.lang.String getPhoneMt() {
		return get("phoneMt");
	}

	public void setDateMt(java.lang.String dateMt) {
		set("dateMt", dateMt);
	}

	public java.lang.String getDateMt() {
		return get("dateMt");
	}

	public void setStatusMtc(java.lang.String statusMtc) {
		set("statusMtc", statusMtc);
	}

	public java.lang.String getStatusMtc() {
		return get("statusMtc");
	}

	public void setDonePd(java.lang.String donePd) {
		set("donePd", donePd);
	}

	public java.lang.String getDonePd() {
		return get("donePd");
	}

	public void setWaitPd(java.lang.String waitPd) {
		set("waitPd", waitPd);
	}

	public java.lang.String getWaitPd() {
		return get("waitPd");
	}

	public void setAddressPd(java.lang.String addressPd) {
		set("addressPd", addressPd);
	}

	public java.lang.String getAddressPd() {
		return get("addressPd");
	}

	public void setOperatorPd(java.lang.String operatorPd) {
		set("operatorPd", operatorPd);
	}

	public java.lang.String getOperatorPd() {
		return get("operatorPd");
	}

	public void setDatePd(java.lang.String datePd) {
		set("datePd", datePd);
	}

	public java.lang.String getDatePd() {
		return get("datePd");
	}

	public void setStatusPdc(java.lang.String statusPdc) {
		set("statusPdc", statusPdc);
	}

	public java.lang.String getStatusPdc() {
		return get("statusPdc");
	}

	public void setPhonePd(java.lang.String phonePd) {
		set("phonePd", phonePd);
	}

	public java.lang.String getPhonePd() {
		return get("phonePd");
	}

	public void setDoneTax(java.lang.String doneTax) {
		set("doneTax", doneTax);
	}

	public java.lang.String getDoneTax() {
		return get("doneTax");
	}

	public void setWaitTax(java.lang.String waitTax) {
		set("waitTax", waitTax);
	}

	public java.lang.String getWaitTax() {
		return get("waitTax");
	}

	public void setAddressTax(java.lang.String addressTax) {
		set("addressTax", addressTax);
	}

	public java.lang.String getAddressTax() {
		return get("addressTax");
	}

	public void setOperatorTax(java.lang.String operatorTax) {
		set("operatorTax", operatorTax);
	}

	public java.lang.String getOperatorTax() {
		return get("operatorTax");
	}

	public void setPhoneTax(java.lang.String phoneTax) {
		set("phoneTax", phoneTax);
	}

	public java.lang.String getPhoneTax() {
		return get("phoneTax");
	}

	public void setDateTax(java.lang.String dateTax) {
		set("dateTax", dateTax);
	}

	public java.lang.String getDateTax() {
		return get("dateTax");
	}

	public void setStatusTaxc(java.lang.String statusTaxc) {
		set("statusTaxc", statusTaxc);
	}

	public java.lang.String getStatusTaxc() {
		return get("statusTaxc");
	}

	public void setOperatorFh(java.lang.String operatorFh) {
		set("operatorFh", operatorFh);
	}

	public java.lang.String getOperatorFh() {
		return get("operatorFh");
	}

	public void setPhoneFh(java.lang.String phoneFh) {
		set("phoneFh", phoneFh);
	}

	public java.lang.String getPhoneFh() {
		return get("phoneFh");
	}

	public void setDateFh(java.lang.String dateFh) {
		set("dateFh", dateFh);
	}

	public java.lang.String getDateFh() {
		return get("dateFh");
	}

	public void setPreTimeFh(java.lang.String preTimeFh) {
		set("preTimeFh", preTimeFh);
	}

	public java.lang.String getPreTimeFh() {
		return get("preTimeFh");
	}

	public void setStatusFhc(java.lang.String statusFhc) {
		set("statusFhc", statusFhc);
	}

	public java.lang.String getStatusFhc() {
		return get("statusFhc");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

}
