/**
 * Copyright (c) 2015-2016, Michael Yang 杨福海 (fuhai999@gmail.com).
 *
 * Licensed under the GNU Lesser General Public License (LGPL) ,Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.jpress.jp.model.base;

import io.jpress.model.Metadata;
import io.jpress.model.core.JModel;
import io.jpress.model.query.MetaDataQuery;
import java.math.BigInteger;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.ehcache.CacheKit;
import com.jfinal.plugin.ehcache.IDataLoader;

/**
 *  Auto generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseContract<M extends BaseContract<M>> extends JModel<M> implements IBean {

	public static final String CACHE_NAME = "contract";
	public static final String METADATA_TYPE = "contract";

	public void removeCache(Object key){
		if(key == null) return;
		CacheKit.remove(CACHE_NAME, key);
	}

	public void putCache(Object key,Object value){
		CacheKit.put(CACHE_NAME, key, value);
	}

	public M getCache(Object key){
		return CacheKit.get(CACHE_NAME, key);
	}

	public M getCache(Object key,IDataLoader dataloader){
		return CacheKit.get(CACHE_NAME, key, dataloader);
	}

	public Metadata createMetadata(){
		Metadata md = new Metadata();
		md.setObjectId(getId());
		md.setObjectType(METADATA_TYPE);
		return md;
	}

	public Metadata createMetadata(String key,String value){
		Metadata md = new Metadata();
		md.setObjectId(getId());
		md.setObjectType(METADATA_TYPE);
		md.setMetaKey(key);
		md.setMetaValue(value);
		return md;
	}

	public boolean saveOrUpdateMetadta(String key,String value){
		Metadata metadata = MetaDataQuery.me().findByTypeAndIdAndKey(METADATA_TYPE, getId(), key);
		if (metadata == null) {
			metadata = createMetadata(key, value);
			return metadata.save();
		}
		metadata.setMetaValue(value);
		return metadata.update();
	}

	@Override
	public boolean equals(Object o) {
		if(o == null){ return false; }
		if(!(o instanceof BaseContract<?>)){return false;}

		BaseContract<?> m = (BaseContract<?>) o;
		if(m.getId() == null){return false;}

		return m.getId().compareTo(this.getId()) == 0;
	}

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		Object id = get("id");
		if (id == null)
			return null;

		return id instanceof BigInteger ? (BigInteger)id : new BigInteger(id.toString());
	}

	public void setOrdersEnterpriseId(java.math.BigInteger ordersEnterpriseId) {
		set("orders_enterprise_id", ordersEnterpriseId);
	}

	public java.math.BigInteger getOrdersEnterpriseId() {
		return get("orders_enterprise_id");
	}

	public void setContractDate(java.util.Date contractDate) {
		set("contract_date", contractDate);
	}

	public java.util.Date getContractDate() {
		return get("contract_date");
	}

	public void setContractDeadline(java.util.Date contractDeadline) {
		set("contract_deadline", contractDeadline);
	}

	public java.util.Date getContractDeadline() {
		return get("contract_deadline");
	}

	public void setContractAmount(java.math.BigDecimal contractAmount) {
		set("contract_amount", contractAmount);
	}

	public java.math.BigDecimal getContractAmount() {
		return get("contract_amount");
	}

	public void setBalanceId(java.math.BigInteger balanceId) {
		set("balanceId", balanceId);
	}

	public java.math.BigInteger getBalanceId() {
		return get("balanceId");
	}

	public void setMonthBalance(java.util.Date monthBalance) {
		set("month_balance", monthBalance);
	}

	public java.util.Date getMonthBalance() {
		return get("month_balance");
	}

	public void setShouldPay(java.math.BigDecimal shouldPay) {
		set("should_pay", shouldPay);
	}

	public java.math.BigDecimal getShouldPay() {
		return get("should_pay");
	}

	public void setMonthShouldPay(java.util.Date monthShouldPay) {
		set("month_should_pay", monthShouldPay);
	}

	public java.util.Date getMonthShouldPay() {
		return get("month_should_pay");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setPayStatus(java.lang.String payStatus) {
		set("pay_status", payStatus);
	}

	public java.lang.String getPayStatus() {
		return get("pay_status");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

}
