/**
 * Copyright (c) 2015-2016, Michael Yang 杨福海 (fuhai999@gmail.com).
 *
 * Licensed under the GNU Lesser General Public License (LGPL) ,Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.jpress.jp.model.base;

import io.jpress.model.Metadata;
import io.jpress.model.core.JModel;
import io.jpress.model.query.MetaDataQuery;
import java.math.BigInteger;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.ehcache.CacheKit;
import com.jfinal.plugin.ehcache.IDataLoader;

/**
 *  Auto generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCash<M extends BaseCash<M>> extends JModel<M> implements IBean {

	public static final String CACHE_NAME = "cash";
	public static final String METADATA_TYPE = "cash";

	public void removeCache(Object key){
		if(key == null) return;
		CacheKit.remove(CACHE_NAME, key);
	}

	public void putCache(Object key,Object value){
		CacheKit.put(CACHE_NAME, key, value);
	}

	public M getCache(Object key){
		return CacheKit.get(CACHE_NAME, key);
	}

	public M getCache(Object key,IDataLoader dataloader){
		return CacheKit.get(CACHE_NAME, key, dataloader);
	}

	public Metadata createMetadata(){
		Metadata md = new Metadata();
		md.setObjectId(getId());
		md.setObjectType(METADATA_TYPE);
		return md;
	}

	public Metadata createMetadata(String key,String value){
		Metadata md = new Metadata();
		md.setObjectId(getId());
		md.setObjectType(METADATA_TYPE);
		md.setMetaKey(key);
		md.setMetaValue(value);
		return md;
	}

	public boolean saveOrUpdateMetadta(String key,String value){
		Metadata metadata = MetaDataQuery.me().findByTypeAndIdAndKey(METADATA_TYPE, getId(), key);
		if (metadata == null) {
			metadata = createMetadata(key, value);
			return metadata.save();
		}
		metadata.setMetaValue(value);
		return metadata.update();
	}

	@Override
	public boolean equals(Object o) {
		if(o == null){ return false; }
		if(!(o instanceof BaseCash<?>)){return false;}

		BaseCash<?> m = (BaseCash<?>) o;
		if(m.getId() == null){return false;}

		return m.getId().compareTo(this.getId()) == 0;
	}

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		Object id = get("id");
		if (id == null)
			return null;

		return id instanceof BigInteger ? (BigInteger)id : new BigInteger(id.toString());
	}

	public void setUserId(java.math.BigInteger userId) {
		set("userId", userId);
	}

	public java.math.BigInteger getUserId() {
		return get("userId");
	}

	public void setMdate(java.lang.String mdate) {
		set("mdate", mdate);
	}

	public java.lang.String getMdate() {
		return get("mdate");
	}

	public void setComName(java.lang.String comName) {
		set("comName", comName);
	}

	public java.lang.String getComName() {
		return get("comName");
	}

	public void setOned(java.lang.String oned) {
		set("oned", oned);
	}

	public java.lang.String getOned() {
		return get("oned");
	}

	public void setOnec(java.lang.String onec) {
		set("onec", onec);
	}

	public java.lang.String getOnec() {
		return get("onec");
	}

	public void setTwod(java.lang.String twod) {
		set("twod", twod);
	}

	public java.lang.String getTwod() {
		return get("twod");
	}

	public void setTwoc(java.lang.String twoc) {
		set("twoc", twoc);
	}

	public java.lang.String getTwoc() {
		return get("twoc");
	}

	public void setThreed(java.lang.String threed) {
		set("threed", threed);
	}

	public java.lang.String getThreed() {
		return get("threed");
	}

	public void setThreec(java.lang.String threec) {
		set("threec", threec);
	}

	public java.lang.String getThreec() {
		return get("threec");
	}

	public void setFourd(java.lang.String fourd) {
		set("fourd", fourd);
	}

	public java.lang.String getFourd() {
		return get("fourd");
	}

	public void setFourc(java.lang.String fourc) {
		set("fourc", fourc);
	}

	public java.lang.String getFourc() {
		return get("fourc");
	}

	public void setSubName(java.lang.String subName) {
		set("subName", subName);
	}

	public java.lang.String getSubName() {
		return get("subName");
	}

	public void setSubCode(java.lang.String subCode) {
		set("subCode", subCode);
	}

	public java.lang.String getSubCode() {
		return get("subCode");
	}

}
