package io.jpress.jp.model;


import java.math.BigInteger;

import io.jpress.jp.model.base.BaseBalance;
import io.jpress.model.core.Table;

/**
 * Generated by JPress.
 */
@Table(tableName="balance",primaryKey="id")
public class Balance extends BaseBalance<Balance> {
	private static final long serialVersionUID = 1L;

	public static final Balance DAO = new Balance();
	
	public Balance findBalanceByUserId(BigInteger userId){
		
		String sql="select * from `balance` where userId = ?";
		
		return findFirst(sql,userId);
	}
}
