package io.jpress.jp.model;

import java.math.BigInteger;
import java.security.PublicKey;
import java.util.List;

import io.jpress.jp.model.base.BaseCash;
import io.jpress.model.core.Table;

/**
 * Generated by JPress.
 */
@Table(tableName="cash",primaryKey="id")
public class Cash extends BaseCash<Cash> {
	private static final long serialVersionUID = 1L;

	public static final Cash DAO = new Cash();
	
	public  List<Cash> findAccountByIdCashs(BigInteger userId,String mdate){

//		String sql = "	SELECT * FROM (SELECT * FROM  cash WHERE contentId = ? AND mdate = ? ) as c  WHERE  subCode IN ('1121','1122','1123','1221','2202')";
		String sql = "	SELECT * FROM `cash` WHERE (userId = ? AND mdate = ? ) AND subCode IN ('1121','1122','1123','1221','2202')";
		return find(sql,userId,mdate);
	}
	
	public List<Cash> findStatisticByIdCashs(BigInteger userId,String mdate){
//		String sql ="select * from (SELECT * FROM  cash WHERE contentId = ? AND mdate = ? ) as c where subCode  like '6001%' ";
		String sql ="select * from `cash`  WHERE (userId = ? AND mdate = ? ) AND subCode  like '6001%' ";
		return find(sql,userId,mdate);
	}

	public List<Cash> findburdenTaxByCashs(BigInteger userId,String mdate){
	//	String sql ="select * from (SELECT * FROM  cash WHERE contentId = ? AND mdate = ? ) as c where subCode  IN ('222101','22210106','22210104','6001','22210102') ";
		String sql ="select * from `cash` WHERE (userId = ? AND mdate = ?) AND subCode  IN ('222101','22210106','22210104','6001','22210102') ";
		return find(sql,userId ,mdate);
	}
	
	public List<Cash> findIncometax(BigInteger userId,String ydate){
//		String sql = "SELECT * FROM `cash` WHERE  mdate > ? AND mdate< ? ORDER BY mdate DESC";
		String sql = "SELECT * FROM `cash` WHERE ( mdate like ? AND userId = ?) AND subCode IN ('222106','6001') ORDER BY mdate DESC";
		return find(sql,ydate+"%",userId);
	}
	
	public List<Cash> findDetailtax(BigInteger userId,String mdate,String mdate1){
		
		String sql="SELECT * FROM `cash` WHERE userId = ? and (mdate between ? and ? ) ORDER BY mdate DESC ";	
		return find(sql,userId,mdate,mdate1);
	}
	
	/**
	 * 查看是否存在
	 */
	public Cash findByBliudCashFlag(BigInteger userId,String mdate){
		String sql = "select * from `cash` where userId =? and mdate = ?";
		return findFirst(sql,userId,mdate);
	}
	
	public List<Cash> findCashByMdateWithContentId(BigInteger userId,String mdate){
		String sql = "select * from `cash` where userId =? and mdate = ?";
		return find(sql,userId,mdate);
	}
	
}
