package io.jpress.jp.model;


import java.math.BigInteger;
import java.util.List;

import io.jpress.jp.model.base.BaseCompanyStock;
import io.jpress.model.core.Table;

/**
 * Generated by JPress.
 */
@Table(tableName="company_stock",primaryKey="id")
public class CompanyStock extends BaseCompanyStock<CompanyStock> {
	private static final long serialVersionUID = 1L;

	public static final CompanyStock DAO = new CompanyStock();
	
	public List<CompanyStock> findByCompanyInfoId(BigInteger companyInfoId){
		String sql = "select * from `company_stock` where company_inof_id = ?";
		return find(sql, companyInfoId);
	}
}
