package io.jpress.jp.model;

import java.math.BigInteger;

import io.jpress.model.core.Table;
import io.jpress.jp.model.base.BaseLastbill;

/**
 * Generated by JPress.
 */
@Table(tableName="lastbill",primaryKey="id")
public class Lastbill extends BaseLastbill<Lastbill> {
	private static final long serialVersionUID = 1L;

	public static final Lastbill DAO = new Lastbill();
	
	public Lastbill findbillById(BigInteger userId,String mdate){
		String sql="select * from `lastbill` where userId =? and mdate = ?";
		return findFirst(sql,userId,mdate);
	}
}
