package io.jpress.jp.model;


import java.math.BigInteger;
import java.util.List;

import com.jfinal.plugin.activerecord.Page;

import io.jpress.jp.model.base.BaseOrdersEnterprise;
import io.jpress.model.core.Table;
import io.jpress.utils.StringUtils;

/**
 * Generated by JPress.
 */
@Table(tableName="orders_enterprise",primaryKey="id")
public class OrdersEnterprise extends BaseOrdersEnterprise<OrdersEnterprise> {
	private static final long serialVersionUID = 1L;

	public static final OrdersEnterprise DAO = new OrdersEnterprise();
	
	public List<OrdersEnterprise> findByFlag(String status){
		String sql = "select oe.*,so.orderType so_orderType from `orders_enterprise` oe left join set_orders so on oe.set_orders_id = so.id where oe.status = ? ORDER BY created DESC";
		return find(sql,status);
	}
	
//	public Page<OrdersEnterprise> paginate(int pageNumber, int pageSize,String status){
//		String sql=" select oe.contactName orders_enterprise_contactName,oe.userId orders_enterprise_userId,oe.id orders_enterprise_id,oe.created orders_enterprise_created,oe.mobile orders_enterprise_mobile,so.orderType so_orderType,u.username user_username,u.company user_company ";
//		StringBuilder fromBuilder=new StringBuilder(" from `orders_enterprise` oe  ");
//		fromBuilder.append(" left join user u on oe.userId = u.id ");
//		fromBuilder.append(" left join set_orders so on oe.set_orders_id = so.id ");
//		fromBuilder.append(" where oe.status = ?  ORDER BY oe.created DESC");
//		return DAO.paginate(pageNumber, pageSize,sql, fromBuilder.toString(),status);
//	}
	public Page<OrdersEnterprise> paginate(int pageNumber, int pageSize,String status,String company){
		String sql=" select oe.contactName orders_enterprise_contactName,oe.userId orders_enterprise_userId,oe.id orders_enterprise_id,oe.created orders_enterprise_created,oe.mobile orders_enterprise_mobile,so.orderType so_orderType,u.username user_username,u.company user_company ";
		StringBuilder fromBuilder=new StringBuilder(" from `orders_enterprise` oe  ");
		fromBuilder.append(" left join user u on oe.userId = u.id ");
		fromBuilder.append(" left join set_orders so on oe.set_orders_id = so.id ");
		fromBuilder.append(" where oe.status = ? ");
		if(StringUtils.isNotBlank(company)){
			fromBuilder.append(" and u.company like ? ORDER BY oe.created DESC");
			return DAO.paginate(pageNumber, pageSize,sql, fromBuilder.toString(),status,"%"+company+"%");
		}else{
			fromBuilder.append(" ORDER BY oe.created DESC");
			return DAO.paginate(pageNumber, pageSize,sql, fromBuilder.toString(),status);
		}
	}
	
	public OrdersEnterprise findDetailById(BigInteger id){
		StringBuilder fromBuilder=new StringBuilder(" select oe.*,so.orderType so_orderType,u.id user_id from `orders_enterprise` oe  ");
		fromBuilder.append(" left join user u on oe.userId = u.id ");
		fromBuilder.append(" left join set_orders so on oe.set_orders_id = so.id ");
		fromBuilder.append(" where oe.id = ? ");
		return findFirst(fromBuilder.toString(),id);
	}
	
	/**
	 * 是否写有合同
	 */
	public OrdersEnterprise findOrdersEnterpriseByStatus(BigInteger userId ,String status){
		String sql = "select * from `orders_enterprise` where userId = ? and status = ?";
		return findFirst(sql,userId, status);
	}
	
	public List<OrdersEnterprise> findOrders(BigInteger userId ,String status){
		String sql = "select * from `orders_enterprise` where userId = ? and status = ?";
		return find(sql,userId, status);
	}
	/**
	 * 是否写有合同
	 */
	public List<OrdersEnterprise> findAllOrdersEnterpriseByStatus(BigInteger userId ,String status){
		String sql = "select * from `orders_enterprise` where userId = ? and status = ?";
		return find(sql,userId, status);
	}
	
	/**
	 * 找订单类
	 */
	public OrdersEnterprise findOrdersEnterpriseById(BigInteger id ){
		String sql = "select s.* from `orders_enterprise` o left join `set_orders` s on o.set_orders_id = s.id where o.id = ? ";
		return findFirst(sql,id);
	}
	
}
