package io.jpress.jp.model;


import java.math.BigInteger;

import com.jfinal.plugin.activerecord.Page;

import io.jpress.jp.model.base.BaseProgress;
import io.jpress.model.core.Table;

/**
 * Generated by JPress.
 */
@Table(tableName="progress",primaryKey="id")
public class Progress extends BaseProgress<Progress> {
	private static final long serialVersionUID = 1L;

	public static final Progress DAO = new Progress();
	
	public Progress findFirstByContentIdAndProgressId(BigInteger userId,BigInteger setProgressId){
		String sql="select * from `progress` where userId= ? and setProgressId= ? ORDER BY created DESC ";
		return findFirst(sql,userId,setProgressId);
	}
	
	public Page<Progress> findPageByUserId(int pageNumber, int pageSize,BigInteger userId){
		String sql  = "select p.*,s.progressType s_progressType ";
		StringBuilder sqlBuilder = new StringBuilder(" from `progress` p");
		sqlBuilder.append(" left join `set_progress` s on p.setProgressId = s.id");
		sqlBuilder.append(" where userId = ?  ORDER BY created DESC");
		return DAO.paginate(pageNumber, pageSize, sql, sqlBuilder.toString(),userId);
	}
}
