package io.jpress.jp.model;


import java.math.BigInteger;
import java.util.List;

import io.jpress.jp.model.base.BaseSetEnterpriseChange;
import io.jpress.model.core.Table;

/**
 * Generated by JPress.
 */
@Table(tableName="set_enterprise_change",primaryKey="id")
public class SetEnterpriseChange extends BaseSetEnterpriseChange<SetEnterpriseChange> {
	private static final long serialVersionUID = 1L;

	public static final SetEnterpriseChange DAO = new SetEnterpriseChange();
	
	public List<SetEnterpriseChange> findAllBySetOrdersId(BigInteger setOrdersId){
		String sql = "select sec.*,so.orderType orderType from `set_enterprise_change` sec left join `set_orders` so on sec.set_orders_id = so.id where set_orders_id = ?";
		return find(sql,setOrdersId);
	}
	public List<SetEnterpriseChange> findAllSetEnterpriseChange(BigInteger setOrdersId){
		String sql = "select * from `set_enterprise_change` where set_orders_id = ?";
		return find(sql,setOrdersId);
	}
	
}
