package io.jpress.jp.model;


import java.util.List;

import io.jpress.jp.model.base.BaseSetUsertype;
import io.jpress.model.core.Table;


/**
 * Generated by JPress.
 */
@Table(tableName="set_usertype",primaryKey="id")
public class SetUsertype extends BaseSetUsertype<SetUsertype> {
	private static final long serialVersionUID = 1L;

	public static final SetUsertype DAO = new SetUsertype();
	
	public List<SetUsertype> findAllSetUserType(){
		String sql="select * from `set_usertype`";
		return find(sql);
	}
}
